//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------



public class HeroData : RawData
{
    
    public string hero_name;
    
    public float max_hp;
    
    public int damage;
    
    public float move_speed;
    
    public int increase_damage;
    
    public float increase_maxhp;
    
    public float increase_movespeed;
    
    public int monster_type;
    
    public string ui_prefab_path;
    
    public string prefab_path;
    
    public string sprite_name;
}
