//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------



public class BuildingData :RawData
{
    
    //public int id;
    
    public string buliding_name;
    
    public string sprite_name;
    
    public int width;
    
    public int height;
    
    public int require_gold;
    
    public int require_wood;
    
    public int require_stone;
    
    public string door_pos;
    
    public string side_door_pos;
    
    public string description;
    
    public string prefab_path;

    public bool required_upgrade;

    public float player_spawn_pos_x;

    public float player_spawn_pos_y;
}
