//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------



public class ToolData : RawData
{
    public string tool_name;
    
    public int type;
    
    public int price;
    
    public int material_item_id;
    
    public int material_amount;
    
    public string sprite_name;
    
    public string description;
}
